apiVersion: v1
kind: Secret
metadata:
  name: cor-auth
  labels:
    {{- include "cor-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  password: {{ required "auth.password is required -- pass with --set-string auth.password=..." .Values.auth.password | quote }}
