apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 00-namespace.yaml
  - 10-pvc.yaml
  - 20-deployment.yaml
  - 30-service.yaml
  - 40-ingress.yaml
images:
  - name: ghcr.io/kamccabe44/cor
    newTag: latest
